- client/package-lock.json
- client/src/views/About.vue
- client/tests/unit/example.spec.js
About page was updated with some better formatting and links. This depends on PR #4 being merged first.
This completes [storyless task 79](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-79).
> T79 new about page

- client/package-lock.json
- client/package.json
- client/public/index.html
- client/src/App.vue
- client/src/components/ExampleForm.vue
- client/src/components/ExampleForm1.vue
- client/src/components/ExampleForm2.vue
- client/src/components/FormWrapper.vue
- client/src/router/index.js
- client/src/views/Create.vue
A drawer component and a place to put the forms for /create route (and potentially for /update route) 
go to localhost:8080/create to view the changes
see files changed tab for changes
~~- [ ] My code has been developer-tested and includes unit tests~~
###Notes:
I remember the tests are scheduled for next week. Does no include any tests in this pr.
- [Ticket](https://the-halo-mod.atlassian.net/browse/HM-88)
> Hm88 scrollable menu and auto snap

- client/package-lock.json
- client/package.json
- client/src/App.vue
- client/src/components/CosmologyForm.vue
- client/src/components/FormNumberField.vue
- client/src/router/index.js
- client/src/views/Home.vue
- server/halomod_app/__init__.py
- server/requirements.txt
This PR implements a form, the Cosmology form, into the front-end. It completes US 90. The form looks like so at the moment:
It has a drop down for selecting the type of cosmology, which automatically updates the values in each field for the defaults for that type. 
The defaults are brought in from the server, where a new endpoint was created called `/constants`. 
Also a re-usable component was added on the front-end that is called `FormNumberField.vue` which can be used to setup your number fields with error handling in an easy way. 
An initial idea for the app model data was added to the `Home.vue` component. 
This had a narrow view of only the cosmo constants, so feel free to modify as needed. But other code might need to be modified if the hierarchy level of `cosmo` is changed because …
> US 90 - Add CosmologyForm

- client/src/components/FilterForm.vue
- client/src/views/Home.vue
This PR implements the Filter form, and satisfies US 96. This PR also depends on #14 to be pulled in first. Otherwise this PR will integrate that PR as well.
- client/src/components/FilterForm.vue 
- client/src/views/Home.vue 
- N/A right now: My code has been developer-tested and includes unit tests
- [US96](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-96)
> US96 Filter Form

- client/src/components/HaloProfileForm.vue
- client/src/views/Home.vue
This PR implements the Halo Profile form, and satisfies US 94. This PR also depends on #14 to be pulled in first. Otherwise this PR will integrate that PR as well.
- client/src/components/HaloProfileForm.vue 
- client/src/views/Home.vue 
- N/A right now: My code has been developer-tested and includes unit tests
- [US94](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-94)
> US94 Halo Profile Form

- client/src/components/HaloModelForm.vue
- client/src/components/InputField.vue
- client/src/constants/backend_constants.js
- client/src/views/Create.vue
Includes updates to the HaloModelForm component so that it can accept v-model style usage.
- client/src/components/HaloModelForm.vue
- client/src/views/Create.vue
> US92 halo model form

- client/package-lock.json
- client/package.json
- client/src/components/HaloModelForm.vue
- client/src/router/index.js
Implemented library that supports material design dual sliders. Also added custom method handling to manipulate the array data coming from the dual slider into the needed rnum, rmax, etc as shown in the second picture. 
Here is the link for the slider component: [https://ej2.syncfusion.com/vue/documentation/slider/getting-started/?no-cache=1](https://ej2.syncfusion.com/vue/documentation/slider/getting-started/?no-cache=1)
package.json
HaloModelForm.vue
router/index.js
> US92-HaloModelForm Added dual slider

- client/src/views/Create.vue
- client/tests/unit/MassDefinitionForm.spec.js
- client/tests/unit/create.spec.js
Adds testing for MassDefinitionForm. Also a couple bug fixes for issues that showed through warnings.
MassDefinitionForm.spec.js contains 5 tests --
- a check to ensure that, when mounted, the form has the correct default model
- a check to ensure that whenever the selected model changes, the parameters also change
- a check to ensure that whenever the selected model changes, the correct fields are rendered
- a check to ensure that whenever the selected model changes, the 'onChange' event is emitted
- a check to ensure that whenever the value of the model parameters change, the 'onChange' event is emitted
Includes:
tests/MassDefinitionForm.spec.js
Developer Checklist:
> US171 T211 Mass Definition Form Testing

- client/tests/unit/GrowthForm.spec.js
Includes content from #51 so that is a prerequisite PR. I may bundle future form tests into larger pull requests since a lot of them follow the same format.
Adds testing for GrowthForm.
GrowthForm.spec.js contains 5 tests --
- a check to ensure that, when mounted, the form has the correct default model
- a check to ensure that whenever the selected model changes, the parameters also change
- a check to ensure that whenever the selected model changes, the correct fields are rendered
- a check to ensure that whenever the selected model changes, the 'onChange' event is emitted
- a check to ensure that whenever the value of the model parameters change, the 'onChange' event is emitted
Includes:
tests/GrowthForm.spec.js
Developer Checklist:
> US171 T212 Growth Form Testing

- client/package-lock.json
- client/package.json
- client/src/main.js
- server/halomod_app/__init__.py
- server/requirements.txt
Add sentry to vue and flask
added sentry sdk and main files of python and vue.
- [] My code has been developer-tested and includes unit tests
division by zero is a test error
- [US 216](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-219)
> HM219Sentry

- client/.eslintrc.js
- client/jest.config.js
- client/package-lock.json
- client/package.json
- client/src/constants/backend_constants.js
- client/tests/immutables.js
This pull request includes:
- Freezes backend constants through js object freezing. 
- One global test to make sure constants don't change
Developer Checklist:
> Hm241 freeze

- client/jest.config.js
- client/src/components/DoubleField.vue
- client/src/components/forms/BiasForm.vue
- client/src/constants/forms.js
- client/src/main.js
- client/src/utils/validators.js
- client/tests/unit/DoubleField.spec.js
- client/tests/unit/validator.spec.js
This is a weird one, folks. DoubleField has been fixed but the only way to do so was to break most existing forms (and many of their tests). Since I'll be diving into generic forms within the next couple of days it didn't make sense to me to manually fix everything in every single form when its about to be replaced anyway. 
As a result, I've created a 'GenericForms' branch which will keep all work related to that tucked away until we can merge it all into dev and I am merging this branch into GenericForms instead of dev.
This PR does a lot:
- introduces a new validator isDefined that verifies that a field isn't empty.
- provides extensive tests for our form validators
- implements a revised DoubleField class that resolves the bug discussed on Monday
- includes extensive tests for the …
> US276 Fix DoubleField

- client/src/components/forms/CosmologyForm.vue
- client/tests/unit/CosmologyForm.spec.js
Adds cosmo tests. Only one file has been changed.
- CosmologyForm.spec.js
- [US 4](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIssue=HM-235)
> HM235 add cosmo tests

- client/src/views/Forms.vue
- client/yarn.lock
Simple but hacky fix for the forms view not scrolling to the correct subform on refresh / manual address input. It forces scroll on the updated lifecycle hook (which happens during a page reload) in the FormView component. Even though created / mounted might sound more 'correct', neither works in this situation.  
- Minor updates to Forms.vue
- 
- There is a lot of chatter online about Vue's scrollBehavior not working properly when used as the docs suggest. It SHOULD be scrolling on refresh/reload and it SHOULD let you use selectors instead of interacting with the DOM directly, but neither of these actually works as expected. Not sure what the deal is but I guess this approach is functional and unobtrusive enough :slightly_frowning_face:
> US270 Fix autoscroll on refresh functionality for forms

- .github/workflows/serverDeployment.yaml
Change branch from master to main
- ServerDeployment.yaml
- [Ticket](https://ticketlink.com)
> Us 196 deploy server: change branch

- client/src/utils/downloads.js
This PR encapsulates changes that were introduced in #96, but resolves all existing merge conflicts that were present when trying to merge dev into that branch. AddInlineCSS method was added to `downloads.js`.
- client/src/utils/downloads.js
N/A
- https://the-halo-mod.atlassian.net/browse/HM-309
> Svg Inline Styles Fix

- .github/workflows/Readme.md
- .github/workflows/client.yaml
- .github/workflows/clientDeployment.yaml
- .github/workflows/server.yaml
- .github/workflows/serverDeployment.yaml
- README.md
- client/README.md
- client/src/views/About.vue
- server/README.md
Just readme and documentation updates.
See files tab for reference
NA
- [HM-319](https://the-halo-mod.atlassian.net/browse/HM-319)
- #89 
- #91 
- #92
> Better documentations

- .github/workflows/clientDeployment.yaml
- client/README.md
- client/public/index.html
This PR implemente [plausible.io](https://plausible.io/) analytics as decided by Steven. It is accessible from [analytics.thehalomod.app](https://analytics.thehalomod.app). The credentials will not be posted here but they will be posted in the slack if you want to take a look, just please don't remove the data for the site. See below for a couple screenshots:
- client/README.md 
- client/public/index.html 
- NA My code has been developer-tested and includes unit tests
- A section was added to the README for the analytics.
- The url for the script tag will need to be changed and a new site will need to be added to the analytics server once the domain for this project is switched to `thehalomod.app`.
- [US 318](https://the-halo-mod.atlassian.net/jira/software/projects/HM/boards/1?selectedIss …
> US 318 Analytics

- .github/workflows/client.yaml
- .github/workflows/clientDeployment.yaml
- .gitignore
- client/package.json
- client/src/components/Forms/GenericForm.vue
- client/src/components/Forms/Parameter.vue
- client/src/components/Graph/index.vue
- client/src/components/Navbar.vue
- client/src/constants/backend_constants.js
- client/src/constants/forms.js
- client/src/constants/model_choices.js
- client/src/constants/parameter_properties.js
- client/src/utils/Store.js
- client/src/utils/plot.js
- client/src/utils/stringUtils.js
- client/src/views/About.vue
- client/src/views/Forms.vue
- client/tests/unit/GenericForm.spec.js
- generate_client_files.sh
- server/generate_version_file.py
- server/halomod_app/__init__.py
- server/halomod_app/endpoint_model.py
- server/halomod_app/endpoint_models.py
- server/halomod_app/endpoint_plot.py
- server/halomod_app/utils.py
- server/run.sh
Resolves a few various issues which are listed below:
- #105 
- #134 
- #140 
- #103 
- #101 
- #102 
- #104 
- #136 
`npm run setup` needs to be ran on the client side before trying this PR out because of the addition of the versions file. 
This was refactored because the code was largely copy and pasted in two places. Due to the requests in #104, it was going to make it so it would need to be copy and pasted again, so it was refactored into its own component. This also reduced the amount of code in `GenericForm` so that was helpful as well. 
- .github/workflows/client.yaml 
- .github/workflows/clientDeployment.yaml 
- client/package.json 
- client/src/components/Forms/GenericForm.vue 
- client/src/components/Graph/index.vue 
- client/src/components/Navbar.vue 
- …
> US 345 Resolve Various Issues

- client/package-lock.json
- client/package.json
- client/src/main.js
- client/src/utils/Store.js
- client/src/utils/downloads.js
- client/yarn.lock
- server/halomod_app/__init__.py
- server/halomod_app/endpoint_plot.py
This PR implements the following:
- Catches and reports UserWarnings
- Axios Retry, this retries any failed connections to the API 3 times
- More data being logged to Sentry for the Frontend Client.
-
- [Ticket](https://ticketlink.com)
> Better Error Reporting

- client/src/constants/backend_constants.js
- client/src/utils/Store.js
- client/tests/unit/GenericForm.spec.js
- server/halomod_app/endpoint_plot.py
Addresses #168.
- client/src/constants/backend_constants.js 
- client/src/utils/Store.js 
- client/tests/unit/GenericForm.spec.js 
- `server/halomod_app/endpoint_plot.py`
- Unused imports and formatting were adjusted in the server side code.
> Comoving R Fix

- .github/workflows/serverDeployment.yaml
Just adds a workflow dispatch option to deploy the server manually.
> Server deploy update
